# Generated by Django 3.2.9 on 2021-11-14 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_img',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='email_address',
            field=models.CharField(max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
