# Generated by Django 3.2.12 on 2022-03-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211114_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='email_address',
            field=models.EmailField(max_length=200),
        ),
    ]
